//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YelhighWebsite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YelhighWebsite.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Check if it works for me :).
        /// </summary>
        internal static string CheckIfItWorks {
            get {
                return ResourceManager.GetString("CheckIfItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Me.
        /// </summary>
        internal static string contact_me {
            get {
                return ResourceManager.GetString("contact_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# Software Engineer.
        /// </summary>
        internal static string CSharpSoftwareEngineer {
            get {
                return ResourceManager.GetString("CSharpSoftwareEngineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building robust, scalable applications with C# and .NET ecosystem. Expertise in ASP.NET Core, Entity Framework, and modern cloud architectures. Creating elegant solutions from backend APIs to responsive frontends.
        /// </summary>
        internal static string CSharpSoftwareEngineerDescription {
            get {
                return ResourceManager.GetString("CSharpSoftwareEngineerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get in Touch.
        /// </summary>
        internal static string get_in_touch {
            get {
                return ResourceManager.GetString("get_in_touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen to My Tracks.
        /// </summary>
        internal static string listen_tracks {
            get {
                return ResourceManager.GetString("listen_tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Listen to me!.
        /// </summary>
        internal static string ListenToMe {
            get {
                return ResourceManager.GetString("ListenToMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating sonic landscapes and crafting beats that move souls. From electronic waves to orchestral arrangements, I bring your audio vision to life. Specializing in EDM, Hip-Hop, and Cinematic Soundtracks..
        /// </summary>
        internal static string MusicProducerDescription {
            get {
                return ResourceManager.GetString("MusicProducerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Producer &amp; Sound Designer.
        /// </summary>
        internal static string MusicProducerSoundDesigner {
            get {
                return ResourceManager.GetString("MusicProducerSoundDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Page not found.
        /// </summary>
        internal static string OopsPageNotFound {
            get {
                return ResourceManager.GetString("OopsPageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Home.
        /// </summary>
        internal static string ReturnToHome {
            get {
                return ResourceManager.GetString("ReturnToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Projects.
        /// </summary>
        internal static string view_projects {
            get {
                return ResourceManager.GetString("view_projects", resourceCulture);
            }
        }
    }
}
